apiVersion: v1
kind: ServiceAccount
metadata:
  name: consumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
        version: v1
    spec:
      serviceAccountName: consumer
      containers:
      - name: consumer
        image: rinormaloku/kafka-consumer
        env:
          - name: SPRING_KAFKA_BOOTSTRAPSERVERS
            value: my-cluster-kafka-bootstrap.kafka:9092
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap.kafka:9092
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
