apiVersion: v1
kind: ServiceAccount
metadata:
  name: producer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
        version: v1
    spec:
      serviceAccountName: producer
      containers:
      - name: producer
        image: rinormaloku/kafka-producer:pr
        env:
          - name: SPRING_KAFKA_BOOTSTRAPSERVERS
            value: my-cluster-kafka-bootstrap.kafka:9092
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap.kafka:9092
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: producer
  name: producer
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: producer